'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MouseMazeDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aero_arrow_48x48x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aero_arrow_48x48x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashle125() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashle125", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashle1251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashle1251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fb_sweepstake_banner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fb_sweepstake_banner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property holidays_red_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holidays_red_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property o_151929b42c5c70a2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("o_151929b42c5c70a2-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property P2s_2_copy_anim1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P2s-2-copy-anim1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property P2s_2_copy_awnim1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P2s-2-copy-awnim1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypal_button_buy_now() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal-button-buy-now", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypal_logo_header_157218() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal-logo-header-157218", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pink160600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink160600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property points2shopbannerghr4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("points2shopbannerghr4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property points2shopbannerpixie647() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("points2shopbannerpixie647", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property points2shopbannertannu5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("points2shopbannertannu5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property points2shopbannerxkritix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("points2shopbannerxkritix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property products468() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("products468", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallKeyG_Large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallKeyG_Large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thecashlogounanimated1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thecashlogounanimated1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property title__2_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("title__2_", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ur1l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ur1l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property url() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("url", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uwrl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uwrl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uwrl1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uwrl1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uwrl2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uwrl2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
